version: 3

env:
  Path: "{{.PWD}}/app/build/tools/nsis/Bin;{{.PWD}}/app/build/tools/upx;{{.PATH}}"

tasks:
  setup:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - go run github.com/fhluo/tools/setup-upx@latest app/build/tools
      - go run github.com/fhluo/tools/setup-nsis@latest app/build/tools

  setup-web:
    dir: ./json2go-web
    cmds:
      - pnpm install

  copy-monaco:
    dir: ./tools/copy-monaco
    cmds:
      - go run .

  build-cli:
    dir: ./json2go-cli
    cmds:
      - go build -o ../json2go-wails/build/bin/json2go-cli.exe

  build-web:
    dir: ./json2go-web
    cmds:
      - pnpm build

  dev-web:
    dir: ./json2go-web
    cmds:
      - pnpm dev

  check-web:
    dir: ./json2go-web
    cmds:
      - pnpm check

  format-web:
    dir: ./json2go-web
    cmds:
      - pnpm format

  build-gui:
    dir: ./json2go-wails
    deps:
      - copy-monaco
    cmds:
      - go run github.com/fhluo/tools/wails-build@latest --upx --path='./build/tools/upx' --nsis --path='./build/tools/nsis/Bin'

  build:
    deps:
      - build-gui
      - build-cli

  dev:
    env:
      json2go_dev: true
      json2go_debug: true
    dir: ./json2go-wails
    deps:
      - copy-monaco
    cmds:
      - wails dev
