version: 3

env:
  Path: "{{.PWD}}/app/build/tools/nsis/Bin;{{.PWD}}/app/build/tools/upx;{{.PATH}}"

tasks:
  setup:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - go run github.com/fhluo/tools/setup-upx@latest app/build/tools
      - go run github.com/fhluo/tools/setup-nsis@latest app/build/tools

  setup-web:
    dir: ./app/ui
    cmds:
      - pnpm install

  copy-monaco:
    dir: ./tools
    cmds:
      - go run ./copy-monaco

  build-cli:
    cmds:
      - go build -o ./app/build/bin/json2go-cli.exe ./cmd/json2go

  build-web:
    dir: ./app/ui
    cmds:
      - pnpm build

  dev-web:
    dir: ./app/ui
    cmds:
      - pnpm dev

  check-web:
    dir: ./app/ui
    cmds:
      - pnpm check

  format-web:
    dir: ./app/ui
    cmds:
      - pnpm format

  build-gui:
    dir: ./app
    deps:
      - copy-monaco
    cmds:
      - go run github.com/fhluo/tools/wails-build@latest --upx --path='./build/tools/upx' --nsis --path='./build/tools/nsis/Bin'

  build:
    deps:
      - build-gui
      - build-cli

  dev:
    env:
      json2go_dev: true
      json2go_debug: true
    dir: ./app
    deps:
      - copy-monaco
    cmds:
      - wails dev
