version: 3

env:
  Path: "{{.PWD}}/app/build/tools/nsis/Bin;{{.PWD}}/app/build/tools/upx;{{.PATH}}"

tasks:
  setup-wails:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest

  setup-web:
    dir: ./json2go-web
    cmds:
      - pnpm install

  setup-upx:
    cmds:
      - go run github.com/fhluo/tools/setup-upx@latest json2go-wails/build/tools

  setup-nsis:
    cmds:
      - go run github.com/fhluo/tools/setup-nsis@latest json2go-wails/build/tools

  setup:
    deps:
      - setup-wails
      - setup-web
      - setup-upx
      - setup-nsis

  build-cli-windows:
    env:
      GOOS: windows
      GOARCH: amd64
    dir: ./json2go-cli
    cmds:
      - go build -o json2go-cli_windows-amd64.exe

  build-cli:
    deps:
      - build-cli-windows

  build-web:
    dir: ./json2go-web
    cmds:
      - pnpm build

  dev-web:
    dir: ./json2go-web
    cmds:
      - pnpm dev

  check-web:
    dir: ./json2go-web
    cmds:
      - pnpm check

  format-web:
    dir: ./json2go-web
    cmds:
      - pnpm format

  copy-monaco:
    dir: ./tools/copy-monaco
    cmds:
      - go run .

  build-wails:
    dir: ./json2go-wails
    deps:
      - copy-monaco
    cmds:
      - go run github.com/fhluo/tools/wails-build@latest --upx --path='./build/tools/upx' --nsis --path='./build/tools/nsis/Bin'

  build:
    deps:
      - build-wails
      - build-cli

  dev:
    env:
      json2go_dev: true
      json2go_debug: true
    dir: ./json2go-wails
    deps:
      - copy-monaco
    cmds:
      - wails dev

  test:
    cmds:
      - go test -v ./json2go/...
      - go test -v ./json2go-cli/...
      - go test -v ./json2go-wails/...
      - go test -v ./tools/copy-monaco/...
