version: 3

tasks:
  install-wails-cli:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest

  copy-monaco:
    dir: ./tools
    cmds:
      - go run ./copy-monaco

  build-cli:
    cmds:
      - go build -o ./app/build/bin/json2go-cli.exe ./cmd/json2go

  build-gui:
    dir: ./app
    deps:
      - copy-monaco
    cmds:
      - wails build

  build:
    deps:
      - build-gui
      - build-cli

  dev:
    deps:
      - copy-monaco
    cmds:
      - wails dev
