version: 3

env:
  Path: "{{.PWD}}/app/build/tools/nsis/Bin;{{.PWD}}/app/build/tools/upx;{{.PATH}}"

includes:
  web:
    taskfile: ./web/Taskfile.yaml
    dir: ./web
  app:
    taskfile: ./app/Taskfile.yaml
    dir: ./app

tasks:
  setup-wails:
    cmd: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

  setup-upx:
    cmd: go run github.com/fhluo/tools/setup-upx@latest app/build/tools

  setup-nsis:
    cmd: go run github.com/fhluo/tools/setup-nsis@latest app/build/tools

  setup:
    deps:
      - setup-wails
      - task: web:install
      - setup-upx
      - setup-nsis

  build-cli-windows:
    env:
      GOOS: windows
      GOARCH: amd64
    dir: cmd/json2go
    cmds:
      - go build -o json2go-cli_windows-amd64.exe

  build-cli:
    deps:
      - build-cli-windows

  build-wails:
    dir: app
    cmds:
#      - go run github.com/fhluo/tools/wails-build@latest --upx --path='./build/tools/upx' --nsis --path='./build/tools/nsis/Bin'
      - wails3 task build

  build:
    deps:
      - build-wails
      - build-cli

  dev:
    env:
      json2go_dev: true
      json2go_debug: true
    dir: app
    deps:
      - copy-monaco
    cmds:
      - wails3 task dev

  test:
    cmds:
      - go test -v ./...
