version: 3

env:
  Path: "{{.PWD}}/app/build/tools/nsis/Bin;{{.PWD}}/app/build/tools/upx;{{.PATH}}"

includes:
  web:
    taskfile: ./web/Taskfile.yaml
    dir: ./web
  app:
    taskfile: ./app/Taskfile.yaml
    dir: ./app

tasks:
  setup-wails:
    cmds:
      - go install github.com/wailsapp/wails/v3/cmd/wails@latest

  setup-web:
    deps:
      - task: web:install

  setup-upx:
    cmds:
      - go run github.com/fhluo/tools/setup-upx@latest json2go-wails/build/tools

  setup-nsis:
    cmds:
      - go run github.com/fhluo/tools/setup-nsis@latest json2go-wails/build/tools

  setup:
    deps:
      - setup-wails
      - setup-web
      - setup-upx
      - setup-nsis

  build-cli-windows:
    env:
      GOOS: windows
      GOARCH: amd64
    dir: cmd/json2go
    cmds:
      - go build -o json2go-cli_windows-amd64.exe

  build-cli:
    deps:
      - build-cli-windows

  build-wails:
    dir: app
    cmds:
      - go run github.com/fhluo/tools/wails-build@latest --upx --path='./build/tools/upx' --nsis --path='./build/tools/nsis/Bin'

  build:
    deps:
      - build-wails
      - build-cli

  dev:
    env:
      json2go_dev: true
      json2go_debug: true
    dir: app
    deps:
      - copy-monaco
    cmds:
      - wails dev

  test:
    cmds:
      - go test -v ./...
