version: 3

tasks:
  install-wails-cli:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest

  install-upx:
    cmds:
      - go run github.com/fhluo/tools/setup-upx@latest app/build/tools

  install-nsis:
    cmds:
      - go run github.com/fhluo/tools/setup-nsis@latest app/build/tools

  install-tools:
    deps:
      - install-upx
      - install-nsis

  install-web-deps:
    dir: ./app/ui
    cmds:
      - pnpm install

  copy-monaco:
    dir: ./tools
    cmds:
      - go run ./copy-monaco

  build-cli:
    cmds:
      - go build -o ./app/build/bin/json2go-cli.exe ./cmd/json2go

  build-gui:
    dir: ./app
    deps:
      - copy-monaco
    cmds:
      - wails build

  build-gui-with-upx-and-nsis:
    dir: ./app
    deps:
      - copy-monaco
    cmds:
      - wails build -upx -nsis

  build:
    deps:
      - build-gui
      - build-cli

  build-with-upx-and-nsis:
    deps:
      - build-gui-with-upx-and-nsis
      - build-cli

  dev:
    deps:
      - copy-monaco
    cmds:
      - wails dev
