// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2) {
  return window['go']['main']['App']['Generate'](arg1, arg2);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function WriteClipboard(arg1) {
  return window['go']['main']['App']['WriteClipboard'](arg1);
}
