// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:string,arg2:Array<string>):Promise<string>;

export function GetFontSize():Promise<number>;

export function GetLocale():Promise<string>;

export function OpenJSONFile():Promise<string>;

export function ReadClipboard():Promise<string>;

export function SaveGoSourceFile(arg1:string):Promise<void>;

export function SetFontSize(arg1:number):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function WriteClipboard(arg1:string):Promise<void>;
