// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2) {
  return window['go']['main']['App']['Generate'](arg1, arg2);
}

export function GetFontSize() {
  return window['go']['main']['App']['GetFontSize']();
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function OpenJSONFile() {
  return window['go']['main']['App']['OpenJSONFile']();
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function SaveGoSourceFile(arg1) {
  return window['go']['main']['App']['SaveGoSourceFile'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function WriteClipboard(arg1) {
  return window['go']['main']['App']['WriteClipboard'](arg1);
}
