// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetAcronyms() {
  return window['go']['main']['App']['GetAcronyms']();
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function SetAcronyms(arg1) {
  return window['go']['main']['App']['SetAcronyms'](arg1);
}

export function WriteClipboard(arg1) {
  return window['go']['main']['App']['WriteClipboard'](arg1);
}
