// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Read(): $CancellablePromise<string> {
    return $Call.ByID(3854646308);
}

export function Write(text: string): $CancellablePromise<void> {
    return $Call.ByID(3958357215, text);
}
