// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetAllCapsWords(): $CancellablePromise<string[] | null> {
    return $Call.ByID(14832671);
}

export function GetFontSize(): $CancellablePromise<number> {
    return $Call.ByID(1925795320);
}

export function GetLocale(): $CancellablePromise<string> {
    return $Call.ByID(107719334);
}

export function GetOptionsGenerateInRealTime(): $CancellablePromise<boolean> {
    return $Call.ByID(317756455);
}

export function GetOptionsValidJSONBeforeGeneration(): $CancellablePromise<boolean> {
    return $Call.ByID(557296779);
}

export function SetAllCapsWords(words: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2314654347, words);
}

export function SetFontSize(size: number): $CancellablePromise<void> {
    return $Call.ByID(2902198964, size);
}

export function SetLocale(locale: string): $CancellablePromise<void> {
    return $Call.ByID(123469194, locale);
}

export function SetOptionsGenerateInRealTime(b: boolean): $CancellablePromise<void> {
    return $Call.ByID(2905123619, b);
}

export function SetOptionsValidJSONBeforeGeneration(valid: boolean): $CancellablePromise<void> {
    return $Call.ByID(885014175, valid);
}
