// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

export function Dialog(): $CancellablePromise<application$0.DialogManager | null> {
    return $Call.ByID(3956783017);
}

export function OpenJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(1072958073);
}

export function SaveGoSourceFile(s: string): $CancellablePromise<void> {
    return $Call.ByID(648126149, s);
}
