// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetAllCapsWords() {
  return window['go']['main']['App']['GetAllCapsWords']();
}

export function GetExamples() {
  return window['go']['main']['App']['GetExamples']();
}

export function GetFontSize() {
  return window['go']['main']['App']['GetFontSize']();
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function GetOptionsGenerateInRealTime() {
  return window['go']['main']['App']['GetOptionsGenerateInRealTime']();
}

export function GetOptionsValidJSONBeforeGeneration() {
  return window['go']['main']['App']['GetOptionsValidJSONBeforeGeneration']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenJSONFile() {
  return window['go']['main']['App']['OpenJSONFile']();
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function SaveGoSourceFile(arg1) {
  return window['go']['main']['App']['SaveGoSourceFile'](arg1);
}

export function SetAllCapsWords(arg1) {
  return window['go']['main']['App']['SetAllCapsWords'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SetOptionsGenerateInRealTime(arg1) {
  return window['go']['main']['App']['SetOptionsGenerateInRealTime'](arg1);
}

export function SetOptionsValidJSONBeforeGeneration(arg1) {
  return window['go']['main']['App']['SetOptionsValidJSONBeforeGeneration'](arg1);
}

export function WriteClipboard(arg1) {
  return window['go']['main']['App']['WriteClipboard'](arg1);
}
