// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DialogManager manages dialog-related operations
 */
export class DialogManager {
    /**
     * Creates a new DialogManager instance.
     * @param {Partial<DialogManager>} [$$source = {}] - The source object to create the DialogManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DialogManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DialogManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DialogManager(/** @type {Partial<DialogManager>} */($$parsedSource));
    }
}
