// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {examples} from '../models';

export function Generate(arg1:string,arg2:Array<string>):Promise<string>;

export function GetAllCapsWords():Promise<Array<string>>;

export function GetExamples():Promise<Array<examples.Example>>;

export function GetFontSize():Promise<number>;

export function GetLatestVersion():Promise<string>;

export function GetLocale():Promise<string>;

export function GetOptionsGenerateInRealTime():Promise<boolean>;

export function GetOptionsValidJSONBeforeGeneration():Promise<boolean>;

export function GetVersion():Promise<string>;

export function OpenJSONFile():Promise<string>;

export function ReadClipboard():Promise<string>;

export function SaveGoSourceFile(arg1:string):Promise<void>;

export function SetAllCapsWords(arg1:Array<string>):Promise<void>;

export function SetFontSize(arg1:number):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetOptionsGenerateInRealTime(arg1:boolean):Promise<void>;

export function SetOptionsValidJSONBeforeGeneration(arg1:boolean):Promise<void>;

export function WriteClipboard(arg1:string):Promise<void>;
