// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function Read() {
    return $Call.ByID(3854646308);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function Write(text) {
    return $Call.ByID(3958357215, text);
}
