// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Read() {
    let $resultPromise = /** @type {any} */($Call.ByID(3854646308));
    return $resultPromise;
}

/**
 * @param {string} text
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Write(text) {
    let $resultPromise = /** @type {any} */($Call.ByID(3958357215, text));
    return $resultPromise;
}
