// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string[]> & { cancel(): void }}
 */
export function GetAllCapsWords() {
    let $resultPromise = /** @type {any} */($Call.ByID(14832671));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<number> & { cancel(): void }}
 */
export function GetFontSize() {
    let $resultPromise = /** @type {any} */($Call.ByID(1925795320));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetLocale() {
    let $resultPromise = /** @type {any} */($Call.ByID(107719334));
    return $resultPromise;
}

/**
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function GetOptionsGenerateInRealTime() {
    let $resultPromise = /** @type {any} */($Call.ByID(317756455));
    return $resultPromise;
}

/**
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function GetOptionsValidJSONBeforeGeneration() {
    let $resultPromise = /** @type {any} */($Call.ByID(557296779));
    return $resultPromise;
}

/**
 * @param {string[]} words
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetAllCapsWords(words) {
    let $resultPromise = /** @type {any} */($Call.ByID(2314654347, words));
    return $resultPromise;
}

/**
 * @param {number} size
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetFontSize(size) {
    let $resultPromise = /** @type {any} */($Call.ByID(2902198964, size));
    return $resultPromise;
}

/**
 * @param {string} locale
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetLocale(locale) {
    let $resultPromise = /** @type {any} */($Call.ByID(123469194, locale));
    return $resultPromise;
}

/**
 * @param {boolean} b
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetOptionsGenerateInRealTime(b) {
    let $resultPromise = /** @type {any} */($Call.ByID(2905123619, b));
    return $resultPromise;
}

/**
 * @param {boolean} valid
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetOptionsValidJSONBeforeGeneration(valid) {
    let $resultPromise = /** @type {any} */($Call.ByID(885014175, valid));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
