// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string[] | null>}
 */
export function GetAllCapsWords() {
    return $Call.ByID(14832671);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetFontSize() {
    return $Call.ByID(1925795320);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLocale() {
    return $Call.ByID(107719334);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetOptionsGenerateInRealTime() {
    return $Call.ByID(317756455);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetOptionsValidJSONBeforeGeneration() {
    return $Call.ByID(557296779);
}

/**
 * @param {string[] | null} words
 * @returns {$CancellablePromise<void>}
 */
export function SetAllCapsWords(words) {
    return $Call.ByID(2314654347, words);
}

/**
 * @param {number} size
 * @returns {$CancellablePromise<void>}
 */
export function SetFontSize(size) {
    return $Call.ByID(2902198964, size);
}

/**
 * @param {string} locale
 * @returns {$CancellablePromise<void>}
 */
export function SetLocale(locale) {
    return $Call.ByID(123469194, locale);
}

/**
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetOptionsGenerateInRealTime(b) {
    return $Call.ByID(2905123619, b);
}

/**
 * @param {boolean} valid
 * @returns {$CancellablePromise<void>}
 */
export function SetOptionsValidJSONBeforeGeneration(valid) {
    return $Call.ByID(885014175, valid);
}
