// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * @returns {$CancellablePromise<application$0.DialogManager | null>}
 */
export function Dialog() {
    return $Call.ByID(3956783017);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function OpenJSONFile() {
    return $Call.ByID(1072958073);
}

/**
 * @param {string} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveGoSourceFile(s) {
    return $Call.ByID(648126149, s);
}
