// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenJSONFile() {
    let $resultPromise = /** @type {any} */($Call.ByID(1072958073));
    return $resultPromise;
}

/**
 * @param {string} s
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveGoSourceFile(s) {
    let $resultPromise = /** @type {any} */($Call.ByID(648126149, s));
    return $resultPromise;
}
