// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetLatestVersion() {
    let $resultPromise = /** @type {any} */($Call.ByID(1370305203));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetVersion() {
    let $resultPromise = /** @type {any} */($Call.ByID(3926490350));
    return $resultPromise;
}
