[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["fhluo <20843637+fhluo@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
