# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

tasks:
  install:
    summary: Install dependencies
    sources:
      - package.json
      - bun.lock
    generates:
      - node_modules/*
    preconditions:
      - sh: bun --version
        msg: "Bun is required. Please install it from https://bun.sh/"
    cmds:
      - bun install

  copy-monaco:
    summary: Copy Monaco Editor assets
    sources:
      - node_modules/monaco-editor/min/vs/**/*
    generates:
      - public/monaco-editor/min/vs/**/*
    cmds:
      - go run ../cmd/copy --src node_modules/monaco-editor/min/vs --dst public/monaco-editor/min/vs assets editor language basic-languages loader.js nls.messages-loader.js 'nls.messages.*.js' '_commonjsHelpers-*.js' 'go-*.js' 'editor.api-*.js' 'jsonMode-*.js' 'cssMode-*.js' 'htmlMode-*.js' 'tsMode-*.js' 'lspLanguageFeatures-*.js' 'workers-*.js'

  build:
    summary: Build the project
    sources:
      - "**/*"
    generates:
      - ../app/ui/dist/*
    deps:
      - install
      - copy-monaco
    cmds:
      - bun run build

  dev:
    summary: Start the development server
    deps:
      - install
      - copy-monaco
    cmds:
      - bun run dev

  check:
    summary: Check the project
    deps:
      - install
    cmds:
      - bun check

  format:
    summary: Format the project
    deps:
      - install
    cmds:
      - bun format
