// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:string):Promise<string>;

export function ReadClipboard():Promise<string>;

export function WriteClipboard(arg1:string):Promise<void>;
