name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.1

      - name: Set up UPX and NSIS
        run: |
          go run .\tools\setup --upx --nsis --token ${{ secrets.GITHUB_TOKEN }}

          $env:Path = (Get-ChildItem -Directory -Path .\build\tools\ | Where-Object { $_.Name -match "^nsis-" }).FullName + "\Bin" + ";" + $env:Path
          $env:Path = (Get-ChildItem -Directory -Path .\build\tools\ | Where-Object { $_.Name -match "^upx-" }).FullName + ";" + $env:Path
          Write-Output $env:Path

      - name: Install frontend dependencies
        run: |
          cd web
          pnpm install
          cd ..

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build CLI
        run: go build -o ./build/bin/json2go-cli.exe ./cmd/json2go

      - name: Build GUI
        run: wails build -nsis -upx

      - name: Test
        run: go test -v ./...
