name: Release Wails

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up Task
        run: |
          winget install --id Task.Task --accept-source-agreements --accept-package-agreements
          "$env:LOCALAPPDATA\Microsoft\WinGet\Links" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Setup
        run: task setup

      - name: Package
        run: task package

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/bin/json2go.exe
            app/build/bin/json2go-amd64-installer.exe
