name: Release Wails

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.27.0-rc.1'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up Nushell
        run: |
          winget install -e --id=Nushell.Nushell --accept-source-agreements --accept-package-agreements
          "$env:LOCALAPPDATA\Programs\nu\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Set up Just
        uses: extractions/setup-just@v4

      - name: Setup Inno Setup
        run: just setup-inno

      - name: Setup UPX
        run: just setup-upx

      - name: Setup
        run: just setup

      - name: Package
        run: just package

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            bin/json2go-${{ github.ref_name }}-windows-amd64-setup.exe
            bin/json2go-cli-${{ github.ref_name }}-windows-amd64.zip
