name: Release

on:
  push:
    tags: ["json2go-cli/v*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Setup
        run: task setup

      - name: Build
        run: task build-cli

      - name: Test
        run: task test

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            json2go-cli/json2go-cli_windows-amd64.exe
