name: Release Wails

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set up Task
        uses: go-task/setup-task@v2

      - name: Setup
        run: task setup

      - name: Package
        run: task package

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            app/build/bin/json2go.exe
            app/build/bin/json2go-amd64-installer.exe
